# _quarto.yml
project:
  type: website
  output-dir: docs

website:
  title: "Ouassil DAHIMENE"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: projects/index.qmd
        text: Projects
        icon: code-square
      - href: about.qmd
        text: About
        icon: person
    right:
      - icon: github
        href: https://github.com/your-username
      - icon: linkedin
        href: https://linkedin.com/in/your-username

  page-footer:
    left: "© 2025 Your Name"
    right: 
      - icon: envelope
        href: mailto:your.email@domain.com

format:
  html:
    theme: [cosmo, custom.scss]
    dark: [darkly, custom.scss]
    css: styles.css
    toc: false
    code-copy: true
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">